In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Telco_customer_churn.xlsx to Telco_customer_churn.xlsx

In [4]:
import os

print(os.listdir())

['.config', 'Telco_customer_churn.xlsx', 'sample_data']

In [5]:
df = pd.read_excel("Telco_customer_churn.xlsx")

df['Total Charges'] = pd.to_numeric(
    df['Total Charges'],
    errors='coerce'
)

df['Total Charges'] = df['Total Charges'].fillna(0)

df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices

In [6]:
drop_cols = [
    'CustomerID',
    'Country',
    'State',
    'City',
    'Zip Code',
    'Lat Long',
    'Latitude',
    'Longitude',
    'Count',
    'Churn Reason'
]

df = df.drop(columns=drop_cols)

In [7]:
df.columns

Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months',
       'Phone Service', 'Multiple Lines', 'Internet Service',
       'Online Security', 'Online Backup', 'Device Protection', 'Tech Support',
       'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label',
       'Churn Value', 'Churn Score', 'CLTV'],
      dtype='object')

In [8]:
le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(
        df[col].astype(str)
    )

In [9]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,...,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV
0,1,0,0,0,2,1,0,0,2,2,...,0,0,1,3,53.85,108.15,1,1,86,3239
1,0,0,0,1,2,1,0,1,0,0,...,0,0,1,2,70.70,151.65,1,1,67,2701
2,0,0,0,1,8,1,2,1,0,0,...,2,0,1,2,99.65,820.50,1,1,86,5372
3,0,0,1,1,28,1,2,1,0,0,...,2,0,1,2,104.80,3046.05,1,1,84,5003
4,1,0,0,1,49,1,2,1,0,2,...,2,0,1,0,103.70,5036.30,1,1,89,5340

In [10]:
y = df['Churn Value']

In [11]:
X = df.drop(
    columns=[
        'Churn Value',
        'Churn Label'
    ]
)

In [13]:
print("Features:", X.shape)
print("Target:", y.shape)

Features: (7043, 21)
Target: (7043,)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [15]:
print(X_train.shape)
print(X_test.shape)

(5634, 21)
(1409, 21)

In [16]:
X.to_csv(
    "customer_features.csv",
    index=False
)

y.to_csv(
    "customer_target.csv",
    index=False
)

In [17]:
feature_summary = pd.DataFrame({
    'Feature': X.columns
})

feature_summary

              Feature
0              Gender
1      Senior Citizen
2             Partner
3          Dependents
4       Tenure Months
5       Phone Service
6      Multiple Lines
7    Internet Service
8     Online Security
9       Online Backup
10  Device Protection
11       Tech Support
12       Streaming TV
13   Streaming Movies
14           Contract
15  Paperless Billing
16     Payment Method
17    Monthly Charges
18      Total Charges
19        Churn Score
20               CLTV